apiVersion: 1

deleteDatasources:
  - name: Reserly Prometheus
    orgId: 1

datasources:
  - name: Reserly Prometheus
    uid: reserly-prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: false
    jsonData:
      httpMethod: POST
      timeInterval: 15s

