spring:
  data:
    redis:
      url: ${RESERLY_REDIS_URL:redis://:reserly-redis-local-only-change-me@localhost:6379}
  datasource:
    url: ${RESERLY_DATABASE_URL:jdbc:postgresql://localhost:5432/reserly?ApplicationName=reserly-api}
    username: ${RESERLY_DATABASE_USERNAME:reserly}
    password: ${RESERLY_DATABASE_PASSWORD:reserly-local-only-change-me}
  rabbitmq:
    addresses: ${RESERLY_RABBITMQ_URL:amqp://reserly:reserly-rabbit-local-only-change-me@localhost:5672}

reserly:
  environment: ${RESERLY_ENVIRONMENT:local}
  apiPublicBaseUrl: ${RESERLY_PUBLIC_BASE_URL:http://localhost:8080}
  webPublicBaseUrl: ${RESERLY_WEB_BASE_URL:http://localhost:3000}
  allowedOrigins: ${RESERLY_ALLOWED_ORIGINS:http://localhost:3000}
  security:
    secureCookies: ${RESERLY_SECURE_COOKIES:false}
  features:
    realPaymentsEnabled: false
